workflows:
  ios-build:
    name: iOS IPA Build
    environment:
      vars:
        APP_STORE_CONNECT_API_KEY: Encrypted(...)
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Run Fastlane to build IPA
        script: bundle exec fastlane build_ipa
    artifacts:
      - build/ios/ipa/*.ipa  # Collects the IPA file as an artifact
    xcode-project:
      automatic-signing: true
      team-id: PHBEM9XP67  # Replace with your Apple Developer Team ID
