workflows:
  ios-build:
    name: iOS IPA Build
    scripts:
      - name: Install dependencies
        script: yarn install  # Install React Native dependencies
      - name: Bundle React Native JS
        script: npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
      - name: Run Fastlane to build IPA
        script: bundle exec fastlane build_ipa  # Runs Fastlane to build IPA
    artifacts:
      - build/ios/ipa/*.ipa  # Collects the IPA file as an artifact
