workflows:
  ios-build:
    name: iOS IPA Build
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Run Fastlane to build IPA
        script: bundle exec fastlane build_ipa
    artifacts:
      - build/ios/ipa/*.ipa  # Collects the IPA file as an artifact
    xcode-project:
      path: ios/rnunitynative.xcodeproj  # Specify the correct path to the Xcode project
